apiVersion: v1
kind: Service #Internal service to allow access to the Postgres PODs
metadata: #Data that helps uniquely identify the object
  name: db #Name of the postgres db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  type: ClusterIP #Type of service we are creating
  ports:
    - targetPort: 5432
      port: 5432
  selector: #to link a service with a set of pods (Postgres in this case)
    name: postgres-pod #name of the selected pod
    app: demo-voting-app #name of the application

