apiVersion: v1
kind: Pod
metadata:
  name: redis-pod #Name of the K8s object (the POD)
  labels: #to allow POD and object differentiation
    name: redis-pod
    app: demo-voting-app #name of the application
spec:
  containers:
    - name: redis #name of the container
      image: redis #image in DockerHub
      ports:
        - containerPort: 6379 #Port on which the application listens